### ISSUE TITLE
elasticsearch/volumes/esdata includes invalid characters for a local volume name, only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed

### ISSUE THREAD

**Issue by snario** [jonbrouse/elk#1]
Fresh clone of this on Ubuntu 14.04 and `docker-compose up` returns this:

```
elasticsearch/volumes/esdata includes invalid characters for a local volume name, only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed
```

**Comment by jonbrouse** [comment]
Sorry for the delay. I'll look into this asap.

**Comment by jonbrouse** [comment]
Compose now enforces a qualified path when declaring volumes. I updated the compose files. Clear out your containers/images and let me know if you are still having issues.
